# Generated by Django 3.2 on 2022-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('authentications', '0004_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='user_agents', to='app.Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banks',
            field=models.ManyToManyField(blank=True, related_name='user_banks', to='app.Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash_in_hps',
            field=models.ManyToManyField(blank=True, related_name='user_cash_in_hps', to='app.CashInHandPerson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='user_companies', to='app.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='user_drivers', to='app.Driver'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expense_heads',
            field=models.ManyToManyField(blank=True, related_name='user_expense_heads', to='app.ExpenseHead'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(blank=True, related_name='user_parties', to='app.Party'),
        ),
    ]
