# Generated by Django 3.2 on 2022-07-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_auto_20220707_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_permissions',
            field=models.JSONField(default=list),
        ),
    ]
